name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    # - name: Install az ml extension
      # run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_GLOBAL}}
    - name: setup
      run: bash setup.sh
      continue-on-error: true 
    - name: Run Azure ML Job
      working-directory: src
      run: |
        az ml job create --file job.yml --resource-group MyLearning --workspace-name AML-Development