# name: Manually trigger an Azure Machine Learning job

# on:
#   push:
#     branches: feature-branch

# jobs:
#   train:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check out repo
#       uses: actions/checkout@main
#     - name: Install az ml extension
#       run: az extension add -n ml -y
#     - name: Azure login
#       uses: azure/login@v1
#       with:
#         creds: ${{secrets.AZURE_CREDENTIALS_GLOBAL}}
#     # - name: 'Az CLI login'
#     #   uses: azure/login@v1
#     #   with:
#     #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
#     #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#     #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#     - name: Show Debug
#       run: az account show
#     # - name: setup
#     #   run: bash setup.sh
#       # continue-on-error: true 
#     - name: Run Azure ML Job
#       working-directory: src
#       run: |
#         az ml job create --file job.yml --resource-group MyLearning --workspace-name AML-Development
