name: Code Verification

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Placeholder
      run: |
        echo "Will add code checks here in the next challenge"